### PR TITLE
add input file *the id still hard code

### PR DESCRIPTION
**Pull request by nibnualdi**
add input file *the id still hard code

### CODE REVIEW

**Comment by nibnualdi** [comment]
jangan dimerge dulu ya... masih hardcode id nya, sama photo profilenya masih dummy

**Comment by nibnualdi** [comment]
sekarang udah bisa dimerge yaa, insyaallah udah solved

**Comment by dutamfr30** [comment]
Aprrove

**Comment by dutamfr30** [comment]
Approve

**Pull request merged**
